# config.yaml
# For non-secret, environment-specific configuration.
# Values here will override DEFAULTS in settings.py.
# Environment variables will override values here.

ALLOWED_HOSTS:
  - "staging.my-app.com"

CORS_ALLOWED_ORIGINS:
  - "https://staging-frontend.my-app.com"

AUTH:
  TEMP_TOKEN_TIMEOUT: 300

QUEST:
  BASE_URL: "https://wj-staging.sjtu.edu.cn/api/v1/public/export"
